apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sciencebeam-autocut-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sciencebeam-autocut-chart.name" . }}
    helm.sh/chart: {{ include "sciencebeam-autocut-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sciencebeam-autocut-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sciencebeam-autocut-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['start-autocut.sh']
          env:
          - name: GUNICORN_WORKERS
            value: "{{ .Values.autocut.workers }}"
          {{ if .Values.autocut.modelPath }}
          - name: AUTOCUT_MODEL_PATH
            value: "{{ .Values.autocut.modelPath }}"
          {{ end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.autocut.testPath }}
              port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.autocut.testPath }}
              port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
